Range-v3: range/v3/utility/any.hpp File Reference
any.hpp File Reference
Classes
struct ranges::any
struct ranges::bad_any_cast
Functions
template<typename T >
meta::if_c< std::is_reference< T >)||copyable< T >, T > ranges::any_cast (any &)
template<typename T >
meta::if_c< std::is_reference< T >)||copyable< T >, T > ranges::any_cast (any const &)
template<typename T >
meta::if_c< std::is_reference< T >)||copyable< T >, T > ranges::any_cast (any &&)
template<typename T >
T * ranges::any_cast (any *) noexcept
template<typename T >
T const * ranges::any_cast (any const *) noexcept
Function Documentation
any_cast() [1/5]
template<typename T > meta::if_c< std::is_reference< T >)||copyable< T >, T > ranges::any_cast (any & x)
Exceptions
bad_any_cast
References ranges::any_cast().
Referenced by ranges::any_cast().
any_cast() [2/5]
template<typename T > meta::if_c< std::is_reference< T >)||copyable< T >, T > ranges::any_cast (any const & x)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References ranges::any_cast().
any_cast() [3/5]
template<typename T > meta::if_c< std::is_reference< T >)||copyable< T >, T > ranges::any_cast (any && x)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References ranges::any_cast().
any_cast() [4/5]
template<typename T > T * ranges::any_cast (any * p) noexcept
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References ranges::any_cast().
any_cast() [5/5]
template<typename T > T const * ranges::any_cast (any const * p) noexcept
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References ranges::any_cast().