Range-v3: Utility
Utility
Description
Utility classes.
Namespaces
ranges::v3
Protect a callable so that it can be safely used in a bind expression without accidentally becoming a "nested" bind.
Classes
struct ranges::v3::adl_advance_detail::advance_fn
struct ranges::v3::as_function_fn
struct ranges::v3::aux::copy_fn
struct ranges::v3::aux::move_fn
struct ranges::v3::back_insert_iterator< Cont >
struct ranges::v3::back_inserter_fn
struct ranges::v3::basic_common_reference< T, U, TQual, UQual >
Users can specialize this to hook the CommonReference concept.
struct ranges::v3::basic_common_reference< basic_iterator< Cur, S >, basic_sentinel< S >, TQual, UQual >
struct ranges::v3::basic_common_reference< basic_sentinel< S >, basic_iterator< Cur, S >, TQual, UQual >
struct ranges::v3::basic_common_reference< T, unreachable, TQual, UQual >
struct ranges::v3::basic_common_reference< unreachable, T, TQual, UQual >
struct ranges::v3::basic_common_reference< unreachable, unreachable, TQual, UQual >
struct ranges::v3::basic_iterator< Cur, S >
struct ranges::v3::basic_mixin< T >
struct ranges::v3::basic_sentinel< S >
struct ranges::v3::bind_element< T >
struct ranges::v3::bind_element< reference_wrapper< T, RValue > >
struct ranges::v3::bind_element< std::reference_wrapper< T > >
struct ranges::v3::bitwise_or
struct ranges::v3::box< Element, Tag, Empty >
struct ranges::v3::box< Element, Tag, true >
struct ranges::v3::coerce< T >
struct ranges::v3::coerce< T & >
struct ranges::v3::coerce< T && >
struct ranges::v3::coerce< T const >
struct ranges::v3::common_reference< Ts >
Users can specialize this to hook the CommonReference concept.
struct ranges::v3::common_reference< T >
struct ranges::v3::common_reference< T, U >
struct ranges::v3::common_reference< T, U, Vs...>
struct ranges::v3::common_type< Ts >
Users should specialize this to hook the Common concept until std gets a SFINAE-friendly std::common_type and there's some sane way to deal with cv and ref qualifiers.
struct ranges::v3::common_type< basic_iterator< Cur, S >, basic_sentinel< S > >
struct ranges::v3::common_type< basic_sentinel< S >, basic_iterator< Cur, S > >
struct ranges::v3::common_type< T >
struct ranges::v3::common_type< T, U >
struct ranges::v3::common_type< T, U, Vs...>
struct ranges::v3::common_type< T, unreachable >
struct ranges::v3::common_type< unreachable, T >
struct ranges::v3::common_type< unreachable, unreachable >
struct ranges::v3::compose_fn
struct ranges::v3::composed< Second, First >
struct ranges::v3::compressed_tuple< Ts >
struct ranges::v3::constant< T, v >
struct ranges::v3::equal_to
struct ranges::v3::expects_wrapped_references< T >
struct ranges::v3::get_cursor_fn
Get a cursor from a basic_iterator.
struct ranges::v3::ident
struct ranges::v3::in_place_t
struct ranges::v3::indirect_fn
struct ranges::v3::indirected< Fn >
struct ranges::v3::is_indirectly_swappable< T, U >
struct ranges::v3::is_nothrow_indirectly_swappable< T, U >
struct ranges::v3::is_nothrow_swappable< T, U >
struct ranges::v3::is_pipeable< T >
struct ranges::v3::is_pipeable< T & >
struct ranges::v3::is_reference_wrapper< T >
struct ranges::v3::is_reference_wrapper< reference_wrapper< T, RValue > >
struct ranges::v3::is_reference_wrapper< std::reference_wrapper< T > >
struct ranges::v3::is_swappable< T, U >
struct ranges::v3::iter_distance_compare_fn
struct ranges::v3::iter_distance_fn
struct ranges::v3::iter_enumerate_fn
struct ranges::v3::iter_move_fn
struct ranges::v3::iter_size_fn
struct ranges::v3::iter_swap_fn
struct ranges::v3::less
struct ranges::v3::logical_negate< Pred >
struct ranges::v3::make_compressed_tuple_fn
struct ranges::v3::make_pipeable_fn
struct ranges::v3::make_tuple_fn
struct ranges::v3::make_unwrap_args_fn
struct ranges::v3::minus
struct ranges::v3::multiplies
struct ranges::v3::mutable_< T >
struct ranges::v3::mutable_< std::atomic< T > >
struct ranges::v3::next_fn
struct ranges::v3::not_fn
struct ranges::v3::ordered_less
struct ranges::v3::ostream_iterator< T, Char, Traits >
struct ranges::v3::overload_fn
struct ranges::v3::overloaded< First, Rest...>
struct ranges::v3::overloaded< Fn >
struct ranges::v3::overloaded<>
struct ranges::v3::pipeable< Derived >
struct ranges::v3::pipeable_access
struct ranges::v3::pipeable_access::impl< Pipeable >
struct ranges::v3::pipeable_base
struct ranges::v3::plus
struct ranges::v3::prev_fn
struct ranges::v3::protect_fn
struct ranges::v3::raw_storage_iterator< O, Val >
struct ranges::v3::ref_fn
struct ranges::v3::reference_of< T >
struct ranges::v3::reference_of< reference_wrapper< T, RValue > >
struct ranges::v3::reference_of< std::reference_wrapper< T > >
struct ranges::v3::reference_of< T & >
struct ranges::v3::reference_of< T && >
struct ranges::v3::reference_of< T const >
struct ranges::v3::reference_wrapper< T, RValue >
struct ranges::v3::referent_of< T >
struct ranges::v3::referent_of< reference_wrapper< T, RValue > >
struct ranges::v3::referent_of< std::reference_wrapper< T > >
struct ranges::v3::referent_of< T & >
struct ranges::v3::referent_of< T && >
struct ranges::v3::referent_of< T const >
struct ranges::v3::rref_fn
struct ranges::v3::semiregular< T >
struct ranges::v3::static_const< T >
struct ranges::v3::tagged_variant< Ts >
struct ranges::v3::tagged_variant_element< N, tagged_variant< Ts...> >
struct ranges::v3::tagged_variant_unique< Var >
struct ranges::v3::tagged_variant_unique< tagged_variant< Ts...> >
struct ranges::v3::tuple_apply_fn
struct ranges::v3::tuple_foldl_fn
struct ranges::v3::tuple_for_each_fn
struct ranges::v3::tuple_transform_fn
struct ranges::v3::unreachable
struct ranges::v3::unwrap_reference_fn
struct ranges::v3::with_braced_init_args< ImplFn >
Typedefs
template<typename T >
using ranges::v3::bind_element_t = meta::_t< bind_element< T >>
template<typename T >
using ranges::v3::forward_ref_t = meta::if_< std::is_reference< T >, reference_wrapper< meta::_t< std::remove_reference< T >>, std::is_rvalue_reference< T >::value >, T && >
template<typename T >
using ranges::v3::function_type = decltype(as_function(std::declval< T >()))
template<typename T >
using ranges::v3::is_reference_wrapper_t = meta::_t< is_reference_wrapper< T >>
template<typename R >
using ranges::v3::aux::move_t = meta::if_< std::is_reference< R >, meta::_t< std::remove_reference< R >> &&, detail::decay_t< R >>
template<typename T >
using ranges::v3::ref_t = decltype(ref(std::declval< T >()))
template<typename T >
using ranges::v3::reference_of_t = meta::_t< reference_of< T >>
template<typename T >
using ranges::v3::referent_of_t = meta::_t< referent_of< T >>
template<typename T >
using ranges::v3::rref_t = decltype(rref(std::declval< T >()))
template<typename T , bool IsConst = false>
using ranges::v3::semiregular_ref_or_val_t = meta::if_< SemiRegular< T >, meta::if_c< IsConst, T, reference_wrapper< T >>, reference_wrapper< meta::apply< meta::add_const_if_c< IsConst >, semiregular< T >>>>
template<typename T >
using ranges::v3::semiregular_t = meta::if_< SemiRegular< T >, T, semiregular< T >>
template<typename Var >
using ranges::v3::tagged_variant_unique_t = typename tagged_variant_unique< Var >::type
template<typename Tup >
using ranges::v3::tuple_indices_t = meta::make_index_sequence< std::tuple_size< typename std::remove_reference< Tup >::type >::value >
template<typename F >
using ranges::v3::unwrap_args_t = decltype(make_unwrap_args(std::declval< F >()))
template<typename T >
using ranges::v3::unwrap_reference_t = decltype(unwrap_reference(std::declval< T >()))
Functions
template<typename T >
constexpr T * ranges::v3::_nullptr_v ()
template<typename T , typename U = meta::if_< std::is_lvalue_reference<T>, std::reference_wrapper<meta::_t<std::remove_reference<T>>>, T &&>>
U ranges::v3::bind_forward (meta::_t< std::remove_reference< T >> &t) noexcept
template<typename T >
T && ranges::v3::bind_forward (meta::_t< std::remove_reference< T >> &&t) noexcept
template<typename T , typename U >
forward_ref_t< T > ranges::v3::forward_ref (U &&t) noexcept
Forward arguments, wrapping lvalue and rvalue refs in ranges::reference_wrapper.
template<typename T >
T & ranges::v3::get (meta::id_t< T > &value)
template<typename T >
T const & ranges::v3::get (meta::id_t< T > const &value)
template<typename T >
T && ranges::v3::get (meta::id_t< T > &&value)
template<std::size_t I, typename... Ts>
auto ranges::v3::get (compressed_tuple< Ts...> &tup) -> decltype(ranges::get< I >(detail::compressed_tuple_core_access::get_data(tup)))
template<std::size_t I, typename... Ts>
constexpr auto ranges::v3::get (compressed_tuple< Ts...> const &tup) -> decltype(ranges::get< I >(detail::compressed_tuple_core_access::get_data(tup)))
template<std::size_t I, typename... Ts>
constexpr auto ranges::v3::get (compressed_tuple< Ts...> &&tup) -> decltype(ranges::get< I >(detail::compressed_tuple_core_access::get_data(detail::move(tup))))
template<typename T >
T & ranges::v3::get (meta::id_t< semiregular< T >> &t)
template<typename T >
T const & ranges::v3::get (meta::id_t< semiregular< T >> const &t)
template<typename T >
T && ranges::v3::get (meta::id_t< semiregular< T >> &&t)
template<typename Tag , typename Element >
Element & ranges::v3::get (box< Element, Tag, false > &b)
template<typename Tag , typename Element >
constexpr Element const & ranges::v3::get (box< Element, Tag, false > const &b)
template<typename Tag , typename Element >
constexpr Element && ranges::v3::get (box< Element, Tag, false > &&b)
template<typename Tag , typename Element >
Element & ranges::v3::get (box< Element, Tag, true > &b)
template<typename Tag , typename Element >
constexpr Element const & ranges::v3::get (box< Element, Tag, true > const &b)
template<typename Tag , typename Element >
constexpr Element && ranges::v3::get (box< Element, Tag, true > &&b)
template<std::size_t I, typename Element >
Element & ranges::v3::get (box< Element, std::integral_constant< std::size_t, I >, false > &b)
template<std::size_t I, typename Element >
constexpr Element const & ranges::v3::get (box< Element, std::integral_constant< std::size_t, I >, false > const &b)
template<std::size_t I, typename Element >
constexpr Element && ranges::v3::get (box< Element, std::integral_constant< std::size_t, I >, false > &&b)
template<std::size_t I, typename Element >
Element & ranges::v3::get (box< Element, std::integral_constant< std::size_t, I >, true > &b)
template<std::size_t I, typename Element >
constexpr Element const & ranges::v3::get (box< Element, std::integral_constant< std::size_t, I >, true > const &b)
template<std::size_t I, typename Element >
constexpr Element && ranges::v3::get (box< Element, std::integral_constant< std::size_t, I >, true > &&b)
template<std::size_t N, typename... Ts>
meta::apply< detail::add_ref_t, tagged_variant_element_t< N, tagged_variant< Ts...> > > ranges::v3::get (tagged_variant< Ts...> &var)
template<std::size_t N, typename... Ts>
meta::apply< detail::add_cref_t, tagged_variant_element_t< N, tagged_variant< Ts...> > > ranges::v3::get (tagged_variant< Ts...> const &var)
template<std::size_t N, typename... Ts>
meta::_t< std::add_rvalue_reference< tagged_variant_element_t< N, tagged_variant< Ts...> > > > ranges::v3::get (tagged_variant< Ts...> &&var)
template<typename I , int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(WeakInputIterator< I >()), int >::type = 0>
counted_iterator< I > ranges::v3::make_counted_iterator (I i, iterator_difference_t< I > n)
template<typename V , typename I , typename D >
counted_iterator< raw_storage_iterator< I, V >, detail::external_count< D > > ranges::v3::make_counted_raw_storage_iterator (I i, D &d)
template<typename I >
reverse_iterator< I > ranges::v3::make_reverse_iterator (I i)
template<typename... Ts, typename... Us, int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(meta::and_c<(bool) EqualityComparable< Ts, Us >()...>::value), int >::type = 0>
bool ranges::v3::operator!= (tagged_variant< Ts...> const &lhs, tagged_variant< Us...> const &rhs)
template<typename I0 , typename D0 , typename I1 , typename D1 , typename CI = detail::UnambiguouslyConvertibleType<I0, I1>, int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(detail::UnambiguouslyConvertible< I0, I1 >()&&!RandomAccessIterator< CI >()), int >::type = 0>
iterator_difference_t< CI > ranges::v3::operator- (counted_iterator< I0, D0 > const &end, counted_iterator< I1, D1 > const &begin)
template<typename I , typename D >
iterator_difference_t< I > ranges::v3::operator- (counted_sentinel const &end, counted_iterator< I, D > const &begin)
template<typename I , typename D >
iterator_difference_t< I > ranges::v3::operator- (counted_iterator< I, D > const &begin, counted_sentinel const &end)
std::ptrdiff_t ranges::v3::operator- (counted_sentinel const &, counted_sentinel const &)
template<typename... Ts, typename... Us, int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(meta::and_c<(bool) EqualityComparable< Ts, Us >()...>::value), int >::type = 0>
bool ranges::v3::operator== (tagged_variant< Ts...> const &lhs, tagged_variant< Us...> const &rhs)
template<typename T , int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(Constructible< detail::decay_t< T >, T && >()), int >::type = 0>
detail::decay_t< T > ranges::v3::aux::operator| (T &&t, copy_fn)
template<typename T >
meta::_t< std::remove_reference< T > > && ranges::v3::aux::operator| (T &&t, move_fn move) noexcept
template<typename Arg , typename Pipe , int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(!is_pipeable< Arg >()&&is_pipeable< Pipe >()), int >::type = 0>
auto ranges::v3::operator| (Arg &&arg, Pipe pipe) -> decltype(pipeable_access::impl< Pipe >::pipe(std::forward< Arg >(arg), pipe))
template<typename Pipe0 , typename Pipe1 , int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(is_pipeable< Pipe0 >()&&is_pipeable< Pipe1 >()), int >::type = 0>
auto ranges::v3::operator| (Pipe0 pipe0, Pipe1 pipe1) -> decltype(make_pipeable(detail::composed_pipe< Pipe0, Pipe1 >
template<std::size_t N, typename... Ts, typename... Args>
void ranges::v3::set (tagged_variant< Ts...> &var, Args &&...args)
template<typename... Ts>
tagged_variant_unique_t< tagged_variant< Ts...> > ranges::v3::unique_variant (tagged_variant< Ts...> const &var)
Variables
static constexpr T ranges::v3::static_const< T >::value {}
Typedef Documentation
template<typename R > using ranges::v3::aux::move_t = typedef meta::if_< std::is_reference<R>, meta::_t<std::remove_reference<R>> &&, detail::decay_t<R>>
#include <range/v3/utility/move.hpp>
See also
move_fn
Function Documentation
template<typename T , int _concept_requires___LINE__ = 42, typename std::enable_if< (_concept_requires___LINE__==43)||(Constructible< detail::decay_t< T >, T && >()), int >::type = 0> detail::decay_t<T> ranges::v3::aux::operator| (T && t, copy_fn)
#include <range/v3/utility/copy.hpp>
See also
copy_fn
References ranges::v3::aux::operator|().
Referenced by ranges::v3::aux::operator|().
template<typename T > meta::_t<std::remove_reference<T> >&& ranges::v3::aux::operator| (T && t, move_fn move) noexcept
#include <range/v3/utility/move.hpp>
See also
move_fn
References ranges::v3::aux::operator|().
Variable Documentation
template<typename T> constexpr T ranges::v3::static_const< T >::value {} static
See also
static_const