var searchData=
[
  ['c_5fstr_2ehpp',['c_str.hpp',['../c__str_8hpp.html',1,'']]],
  ['c_5fstr_5ffn',['c_str_fn',['../structranges_1_1views_1_1c__str__fn.html',1,'ranges::views']]],
  ['cache1_2ehpp',['cache1.hpp',['../cache1_8hpp.html',1,'']]],
  ['cache1_5ffn',['cache1_fn',['../structranges_1_1views_1_1cache1__fn.html',1,'ranges::views']]],
  ['cache1_5fview',['cache1_view',['../structranges_1_1cache1__view.html',1,'ranges']]],
  ['cartesian_5fproduct',['cartesian_product',['../group__transformation.html#ga5e408243147a04c1ca2742211e3c0982',1,'meta::cartesian_product()'],['../group__lazy__transformation.html#ga7618cffe976d0c5158c683c9186c4af0',1,'meta::lazy::cartesian_product()']]],
  ['cartesian_5fproduct_2ehpp',['cartesian_product.hpp',['../cartesian__product_8hpp.html',1,'']]],
  ['cartesian_5fproduct_5ffn',['cartesian_product_fn',['../structranges_1_1views_1_1cartesian__product__fn.html',1,'ranges::views']]],
  ['cartesian_5fproduct_5fview',['cartesian_product_view',['../structranges_1_1cartesian__product__view.html',1,'ranges']]],
  ['category',['category',['../any__view_8hpp.html#a37595c031f4d0249cede2046f4254c93',1,'ranges']]],
  ['cbegin',['cbegin',['../group__group-range.html#ga8dacb30d01871a666d9bb02d33530da9',1,'ranges']]],
  ['cdata',['cdata',['../group__group-range.html#ga1c3359d1155f499d6a766f0b31c76b06',1,'ranges']]],
  ['cend',['cend',['../group__group-range.html#gaef3de204c8e48b13ef770a77ab7f0c89',1,'ranges']]],
  ['cend_5fcursor_5ffn',['cend_cursor_fn',['../structranges_1_1join__view_1_1cend__cursor__fn.html',1,'ranges::join_view']]],
  ['char_5f',['char_',['../group__integral.html#ga22c6fcac17e490346cbe68750a6a9d2f',1,'meta']]],
  ['chunk_2ehpp',['chunk.hpp',['../chunk_8hpp.html',1,'']]],
  ['chunk_5fbase_5ffn',['chunk_base_fn',['../structranges_1_1views_1_1chunk__base__fn.html',1,'ranges::views']]],
  ['chunk_5ffn',['chunk_fn',['../structranges_1_1views_1_1chunk__fn.html',1,'ranges::views']]],
  ['chunk_5fview',['chunk_view',['../structranges_1_1chunk__view.html',1,'ranges']]],
  ['chunk_5fview_5f',['chunk_view_',['../structranges_1_1chunk__view__.html',1,'ranges']]],
  ['chunk_5fview_5f_3c_20rng_2c_20false_20_3e',['chunk_view_&lt; Rng, false &gt;',['../structranges_1_1chunk__view___3_01_rng_00_01false_01_4.html',1,'ranges']]],
  ['chunk_5fview_5f_3c_20rng_2c_28bool_29_20forward_5frange_3c_20rng_20_3e_20_3e',['chunk_view_&lt; Rng,(bool) forward_range&lt; Rng &gt; &gt;',['../structranges_1_1chunk__view__.html',1,'ranges']]],
  ['closed_5findices_5ffn',['closed_indices_fn',['../structranges_1_1views_1_1closed__indices__fn.html',1,'ranges::views']]],
  ['closed_5fiota_5ffn',['closed_iota_fn',['../structranges_1_1views_1_1closed__iota__fn.html',1,'ranges::views']]],
  ['closed_5fiota_5fview',['closed_iota_view',['../structranges_1_1closed__iota__view.html',1,'ranges']]],
  ['coerce',['coerce',['../structranges_1_1coerce.html',1,'ranges']]],
  ['coerce_3c_20t_20_26_20_3e',['coerce&lt; T &amp; &gt;',['../structranges_1_1coerce_3_01_t_01_6_01_4.html',1,'ranges']]],
  ['coerce_3c_20t_20_26_26_20_3e',['coerce&lt; T &amp;&amp; &gt;',['../structranges_1_1coerce_3_01_t_01_6_6_01_4.html',1,'ranges']]],
  ['coerce_3c_20t_20const_20_3e',['coerce&lt; T const &gt;',['../structranges_1_1coerce_3_01_t_01const_01_4.html',1,'ranges']]],
  ['common_2ehpp',['common.hpp',['../common_8hpp.html',1,'']]],
  ['common_5ffn',['common_fn',['../structranges_1_1views_1_1common__fn.html',1,'ranges::views']]],
  ['common_5fiterator',['common_iterator',['../structranges_1_1common__iterator.html',1,'ranges']]],
  ['common_5fiterator_2ehpp',['common_iterator.hpp',['../common__iterator_8hpp.html',1,'']]],
  ['common_5fpair',['common_pair',['../structranges_1_1common__pair.html',1,'ranges']]],
  ['common_5frange_5ftag',['common_range_tag',['../structranges_1_1common__range__tag.html',1,'ranges']]],
  ['common_5freference',['common_reference',['../structconcepts_1_1common__reference.html',1,'concepts']]],
  ['common_5freference_3c_20t_20_3e',['common_reference&lt; T &gt;',['../structconcepts_1_1common__reference_3_01_t_01_4.html',1,'concepts']]],
  ['common_5freference_3c_20t_2c_20u_20_3e',['common_reference&lt; T, U &gt;',['../structconcepts_1_1common__reference_3_01_t_00_01_u_01_4.html',1,'concepts']]],
  ['common_5freference_3c_20t_2c_20u_2c_20vs_2e_2e_2e_20_3e',['common_reference&lt; T, U, Vs... &gt;',['../structconcepts_1_1common__reference_3_01_t_00_01_u_00_01_vs_8_8_8_01_4.html',1,'concepts']]],
  ['common_5ftuple',['common_tuple',['../structranges_1_1common__tuple.html',1,'ranges']]],
  ['common_5ftuple_2ehpp',['common_tuple.hpp',['../common__tuple_8hpp.html',1,'']]],
  ['common_5ftype',['common_type',['../structconcepts_1_1common__type.html',1,'concepts']]],
  ['common_5ftype_2ehpp',['common_type.hpp',['../common__type_8hpp.html',1,'']]],
  ['common_5ftype_3c_20t_20_3e',['common_type&lt; T &gt;',['../structconcepts_1_1common__type_3_01_t_01_4.html',1,'concepts']]],
  ['common_5ftype_3c_20t_2c_20u_20_3e',['common_type&lt; T, U &gt;',['../structconcepts_1_1common__type_3_01_t_00_01_u_01_4.html',1,'concepts']]],
  ['common_5ftype_3c_20t_2c_20u_2c_20vs_2e_2e_2e_20_3e',['common_type&lt; T, U, Vs... &gt;',['../structconcepts_1_1common__type_3_01_t_00_01_u_00_01_vs_8_8_8_01_4.html',1,'concepts']]],
  ['common_5fview',['common_view',['../structranges_1_1common__view.html',1,'ranges']]],
  ['common_5fview_3c_20rng_2c_20true_20_3e',['common_view&lt; Rng, true &gt;',['../structranges_1_1common__view_3_01_rng_00_01true_01_4.html',1,'ranges']]],
  ['comparisons_2ehpp',['comparisons.hpp',['../comparisons_8hpp.html',1,'']]],
  ['compose',['compose',['../group__lazy__composition.html#ga3174f1e6fadebf7d11f3934c93911706',1,'meta::lazy::compose()'],['../group__group-functional.html#gaed1c38a1e34a739ee4fd474aaafbcb30',1,'ranges::compose()']]],
  ['compose_2ehpp',['compose.hpp',['../compose_8hpp.html',1,'']]],
  ['compose_5f',['compose_',['../structmeta_1_1compose__.html',1,'meta']]],
  ['compose_5f_3c_20fn0_20_3e',['compose_&lt; Fn0 &gt;',['../structmeta_1_1compose___3_01_fn0_01_4.html',1,'meta']]],
  ['compose_5f_3c_20fn0_2c_20fns_2e_2e_2e_20_3e',['compose_&lt; Fn0, Fns... &gt;',['../structmeta_1_1compose___3_01_fn0_00_01_fns_8_8_8_01_4.html',1,'meta']]],
  ['compose_5ffn',['compose_fn',['../structranges_1_1compose__fn.html',1,'ranges']]],
  ['composed',['composed',['../structranges_1_1composed.html',1,'ranges']]],
  ['composition',['Composition',['../group__composition.html',1,'']]],
  ['compressed_5fpair',['compressed_pair',['../structranges_1_1compressed__pair.html',1,'ranges']]],
  ['compressed_5fpair_2ehpp',['compressed_pair.hpp',['../compressed__pair_8hpp.html',1,'']]],
  ['compressed_5fpair_3c_20basesent_2c_20adapt_20_3e',['compressed_pair&lt; BaseSent, Adapt &gt;',['../structranges_1_1compressed__pair.html',1,'ranges']]],
  ['concat',['concat',['../group__lazy__transformation.html#gab2a5a4b7b5c4542f2d2009a239c4fcea',1,'meta::lazy']]],
  ['concat_2ehpp',['concat.hpp',['../concat_8hpp.html',1,'']]],
  ['concat_5f',['concat_',['../group__transformation.html#ga8d0d695134bd6b94698ae4f1c0d2f553',1,'meta']]],
  ['concat_5ffn',['concat_fn',['../structranges_1_1views_1_1concat__fn.html',1,'ranges::views']]],
  ['concat_5fview',['concat_view',['../structranges_1_1concat__view.html',1,'ranges']]],
  ['concepts_2ehpp',['concepts.hpp',['../concepts_2concepts_8hpp.html',1,'(Global Namespace)'],['../range_2v3_2action_2concepts_8hpp.html',1,'(Global Namespace)'],['../range_2v3_2functional_2concepts_8hpp.html',1,'(Global Namespace)'],['../range_2v3_2iterator_2concepts_8hpp.html',1,'(Global Namespace)'],['../range_2v3_2range_2concepts_8hpp.html',1,'(Global Namespace)']]],
  ['const_2ehpp',['const.hpp',['../const_8hpp.html',1,'']]],
  ['const_5ffn',['const_fn',['../structranges_1_1views_1_1const__fn.html',1,'ranges::views']]],
  ['const_5fview',['const_view',['../structranges_1_1const__view.html',1,'ranges']]],
  ['contains',['contains',['../group__group-algorithms.html#ga20cc9a6f2eaf8f090470a5e87c7e8264',1,'ranges::contains(I first, S last, const T &amp;val, P proj={}) -&gt; bool requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; I, P &gt;, const T * &gt;'],['../group__group-algorithms.html#ga01a62ccee18d1fec2e634bb3141e8582',1,'ranges::contains(Rng &amp;&amp;rng, const T &amp;val, P proj={}) -&gt; bool requires input_range&lt; Rng &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; iterator_t&lt; Rng &gt;, P &gt;, const T * &gt;']]],
  ['contains_2ehpp',['contains.hpp',['../contains_8hpp.html',1,'']]],
  ['contiguous_5fiterator_5ftag',['contiguous_iterator_tag',['../structranges_1_1contiguous__iterator__tag.html',1,'ranges']]],
  ['contiguous_5frange_5ftag',['contiguous_range_tag',['../structranges_1_1contiguous__range__tag.html',1,'ranges']]],
  ['conversion_2ehpp',['conversion.hpp',['../conversion_8hpp.html',1,'']]],
  ['convert_5fto',['convert_to',['../structranges_1_1convert__to.html',1,'ranges']]],
  ['copy',['copy',['../group__group-utility.html#gaa77a9f8d78fe2ed9c14bde30e7523746',1,'ranges::aux::copy()'],['../group__group-algorithms.html#ga83cdf5c653cd6f7b6d18deaab905cdd9',1,'ranges::copy(I first, S last, O out) -&gt; copy_result&lt; I, O &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirectly_copyable&lt; I, O &gt;'],['../group__group-algorithms.html#ga917adb24d7ee65882cf576a5a4c5228d',1,'ranges::copy(Rng &amp;&amp;rng, O out) -&gt; copy_result&lt; safe_iterator_t&lt; Rng &gt;, O &gt; requires input_range&lt; Rng &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirectly_copyable&lt; iterator_t&lt; Rng &gt;, O &gt;']]],
  ['copy_2ehpp',['copy.hpp',['../algorithm_2copy_8hpp.html',1,'(Global Namespace)'],['../utility_2copy_8hpp.html',1,'(Global Namespace)']]],
  ['copy_5fbackward',['copy_backward',['../group__group-algorithms.html#ga1440e2b669271bb83e34324338757caf',1,'ranges::copy_backward(I first, S end_, O out) -&gt; copy_backward_result&lt; I, O &gt; requires bidirectional_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;bidirectional_iterator&lt; O &gt; &amp;&amp;indirectly_copyable&lt; I, O &gt;'],['../group__group-algorithms.html#ga908b242ebc91d53a3f38ce24d01493b1',1,'ranges::copy_backward(Rng &amp;&amp;rng, O out) -&gt; copy_backward_result&lt; safe_iterator_t&lt; Rng &gt;, O &gt; requires bidirectional_range&lt; Rng &gt; &amp;&amp;bidirectional_iterator&lt; O &gt; &amp;&amp;indirectly_copyable&lt; iterator_t&lt; Rng &gt;, O &gt;']]],
  ['copy_5fbackward_2ehpp',['copy_backward.hpp',['../copy__backward_8hpp.html',1,'']]],
  ['copy_5ffn',['copy_fn',['../structranges_1_1aux_1_1copy__fn.html',1,'ranges::aux']]],
  ['copy_5fif',['copy_if',['../group__group-algorithms.html#ga9c7793e127e9f16451b8e2869ca8be78',1,'ranges::copy_if(I first, S last, O out, F pred, P proj=P{}) -&gt; copy_if_result&lt; I, O &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; I, P &gt;&gt; &amp;&amp;indirectly_copyable&lt; I, O &gt;'],['../group__group-algorithms.html#gacf2c0297eeb25e9a6fd9d1323f4eb967',1,'ranges::copy_if(Rng &amp;&amp;rng, O out, F pred, P proj=P{}) -&gt; copy_if_result&lt; safe_iterator_t&lt; Rng &gt;, O &gt; requires input_range&lt; Rng &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt; &amp;&amp;indirectly_copyable&lt; iterator_t&lt; Rng &gt;, O &gt;']]],
  ['copy_5fif_2ehpp',['copy_if.hpp',['../copy__if_8hpp.html',1,'']]],
  ['copy_5fn',['copy_n',['../group__group-algorithms.html#ga5dfbdb6265d19283095c021a2891bc5d',1,'ranges']]],
  ['copy_5fn_2ehpp',['copy_n.hpp',['../copy__n_8hpp.html',1,'']]],
  ['copy_5ftag',['copy_tag',['../structranges_1_1copy__tag.html',1,'ranges']]],
  ['core_2ehpp',['core.hpp',['../core_8hpp.html',1,'']]],
  ['count',['count',['../group__query.html#ga8a395b36c7a028e67cf7cbaa28ab3ccc',1,'meta::count()'],['../group__lazy__query.html#ga44cd30c6742c876e0ecef6e741c1b10f',1,'meta::lazy::count()'],['../group__group-algorithms.html#ga0a6302f276cdf98372e30f45d10ae3a4',1,'ranges::count(I first, S last, V const &amp;val, P proj=P{}) -&gt; iter_difference_t&lt; I &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; I, P &gt;, V const * &gt;'],['../group__group-algorithms.html#gae2ef1075d6f1f102246b50dff5e01eda',1,'ranges::count(Rng &amp;&amp;rng, V const &amp;val, P proj=P{}) -&gt; iter_difference_t&lt; iterator_t&lt; Rng &gt;&gt; requires input_range&lt; Rng &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; iterator_t&lt; Rng &gt;, P &gt;, V const * &gt;']]],
  ['count_2ehpp',['count.hpp',['../count_8hpp.html',1,'']]],
  ['count_5f',['count_',['../structmeta_1_1detail_1_1count__.html',1,'meta::detail']]],
  ['count_5f_3c_20list_3c_20l_2e_2e_2e_20_3e_2c_20t_20_3e',['count_&lt; list&lt; L... &gt;, T &gt;',['../structmeta_1_1detail_1_1count___3_01list_3_01_l_8_8_8_01_4_00_01_t_01_4.html',1,'meta::detail']]],
  ['count_5f_3c_20list_3c_3e_2c_20t_20_3e',['count_&lt; list&lt;&gt;, T &gt;',['../structmeta_1_1detail_1_1count___3_01list_3_4_00_01_t_01_4.html',1,'meta::detail']]],
  ['count_5fif',['count_if',['../group__query.html#ga665bd44f6d231438a3200df8030f593a',1,'meta::count_if()'],['../group__lazy__query.html#gae2490225acf969acd94baf974a99c4f8',1,'meta::lazy::count_if()'],['../group__group-algorithms.html#gaa6d7932d258fee27a78a08afefdeda1b',1,'ranges::count_if(I first, S last, R pred, P proj=P{}) -&gt; iter_difference_t&lt; I &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_unary_predicate&lt; R, projected&lt; I, P &gt;&gt;'],['../group__group-algorithms.html#ga8a066f39ca76bf1389b93ffd55720f7e',1,'ranges::count_if(Rng &amp;&amp;rng, R pred, P proj=P{}) -&gt; iter_difference_t&lt; iterator_t&lt; Rng &gt;&gt; requires input_range&lt; Rng &gt; &amp;&amp;indirect_unary_predicate&lt; R, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt;']]],
  ['count_5fif_2ehpp',['count_if.hpp',['../count__if_8hpp.html',1,'']]],
  ['count_5fif_5f',['count_if_',['../structmeta_1_1detail_1_1count__if__.html',1,'meta::detail']]],
  ['count_5fif_5f_3c_20list_3c_20l_2e_2e_2e_20_3e_2c_20fn_2c_20void_5f_3c_20integer_5fsequence_3c_20bool_2c_20bool_28invoke_3c_20fn_2c_20l_20_3e_3a_3atype_3a_3avalue_29_2e_2e_2e_20_3e_20_3e_20_3e',['count_if_&lt; list&lt; L... &gt;, Fn, void_&lt; integer_sequence&lt; bool, bool(invoke&lt; Fn, L &gt;::type::value)... &gt; &gt; &gt;',['../structmeta_1_1detail_1_1count__if___3_01list_3_01_l_8_8_8_01_4_00_01_fn_00_01void___3_01integer_5f827808f61383ae58cc36c01904f2fc.html',1,'meta::detail']]],
  ['count_5fif_5f_3c_20list_3c_3e_2c_20fn_20_3e',['count_if_&lt; list&lt;&gt;, Fn &gt;',['../structmeta_1_1detail_1_1count__if___3_01list_3_4_00_01_fn_01_4.html',1,'meta::detail']]],
  ['counted_2ehpp',['counted.hpp',['../counted_8hpp.html',1,'']]],
  ['counted_5ffn',['counted_fn',['../structranges_1_1views_1_1counted__fn.html',1,'ranges::views']]],
  ['counted_5fiterator_2ehpp',['counted_iterator.hpp',['../counted__iterator_8hpp.html',1,'']]],
  ['counted_5fview',['counted_view',['../structranges_1_1counted__view.html',1,'ranges']]],
  ['cpp20_5fcommon_5ffn',['cpp20_common_fn',['../structranges_1_1views_1_1cpp20__common__fn.html',1,'ranges::views']]],
  ['cpp20_5fcounted_5ffn',['cpp20_counted_fn',['../structranges_1_1views_1_1cpp20__counted__fn.html',1,'ranges::views']]],
  ['cpp20_5ffilter_5fbase_5ffn',['cpp20_filter_base_fn',['../structranges_1_1views_1_1cpp20__filter__base__fn.html',1,'ranges::views']]],
  ['cpp20_5ffilter_5ffn',['cpp20_filter_fn',['../structranges_1_1views_1_1cpp20__filter__fn.html',1,'ranges::views']]],
  ['cpp20_5fjoin_5ffn',['cpp20_join_fn',['../structranges_1_1views_1_1cpp20__join__fn.html',1,'ranges::views']]],
  ['crbegin',['crbegin',['../group__group-range.html#ga77a2be5a9ab4b5f662866ec619a5bec7',1,'ranges']]],
  ['crend',['crend',['../group__group-range.html#gabec3e854e6186c4bc6f1d365bfaabb0a',1,'ranges']]],
  ['curry',['curry',['../group__composition.html#gaf3f1c009ba67c7274eedea5bf9442c27',1,'meta::curry()'],['../group__lazy__composition.html#gaa7bb638895f060caafb347e38253ce40',1,'meta::lazy::curry()']]],
  ['cursor',['cursor',['../structranges_1_1join__view_1_1cursor.html',1,'ranges::join_view&lt; Rng &gt;::cursor&lt; Const &gt;'],['../classranges_1_1join__with__view_1_1cursor.html',1,'ranges::join_with_view&lt; Rng, ValRng &gt;::cursor']]],
  ['cycle_2ehpp',['cycle.hpp',['../cycle_8hpp.html',1,'']]],
  ['cycle_5ffn',['cycle_fn',['../structranges_1_1views_1_1cycle__fn.html',1,'ranges::views']]],
  ['cycled_5fview',['cycled_view',['../structranges_1_1cycled__view.html',1,'ranges::cycled_view&lt; Rng, bool &gt;'],['../structranges_1_1cycled__view.html#aa31042ba35997c191f70557600daba1e',1,'ranges::cycled_view::cycled_view()']]],
  ['cycled_5fview_3c_20rng_2c_20true_20_3e',['cycled_view&lt; Rng, true &gt;',['../structranges_1_1cycled__view_3_01_rng_00_01true_01_4.html',1,'ranges']]]
];
