var searchData=
[
  ['sample_5fbase_5ffn',['sample_base_fn',['../structranges_1_1views_1_1sample__base__fn.html',1,'ranges::views']]],
  ['sample_5ffn',['sample_fn',['../structranges_1_1views_1_1sample__fn.html',1,'ranges::views']]],
  ['sample_5fview',['sample_view',['../classranges_1_1sample__view.html',1,'ranges']]],
  ['scope_5fexit',['scope_exit',['../structranges_1_1scope__exit.html',1,'ranges']]],
  ['semiregular_5fbox',['semiregular_box',['../structranges_1_1semiregular__box.html',1,'ranges']]],
  ['semiregular_5fbox_3c_20t_20_26_20_3e',['semiregular_box&lt; T &amp; &gt;',['../structranges_1_1semiregular__box_3_01_t_01_6_01_4.html',1,'ranges']]],
  ['semiregular_5fbox_3c_20t_20_26_26_20_3e',['semiregular_box&lt; T &amp;&amp; &gt;',['../structranges_1_1semiregular__box_3_01_t_01_6_6_01_4.html',1,'ranges']]],
  ['sentinel_5ftag',['sentinel_tag',['../structranges_1_1sentinel__tag.html',1,'ranges']]],
  ['set',['set',['../classset.html',1,'']]],
  ['set_5fdifference_5fbase_5ffn',['set_difference_base_fn',['../structranges_1_1views_1_1set__difference__base__fn.html',1,'ranges::views']]],
  ['set_5fdifference_5ffn',['set_difference_fn',['../structranges_1_1views_1_1set__difference__fn.html',1,'ranges::views']]],
  ['set_5fintersection_5fbase_5ffn',['set_intersection_base_fn',['../structranges_1_1views_1_1set__intersection__base__fn.html',1,'ranges::views']]],
  ['set_5fintersection_5ffn',['set_intersection_fn',['../structranges_1_1views_1_1set__intersection__fn.html',1,'ranges::views']]],
  ['set_5fsymmetric_5fdifference_5fbase_5ffn',['set_symmetric_difference_base_fn',['../structranges_1_1views_1_1set__symmetric__difference__base__fn.html',1,'ranges::views']]],
  ['set_5fsymmetric_5fdifference_5ffn',['set_symmetric_difference_fn',['../structranges_1_1views_1_1set__symmetric__difference__fn.html',1,'ranges::views']]],
  ['set_5funion_5fbase_5ffn',['set_union_base_fn',['../structranges_1_1views_1_1set__union__base__fn.html',1,'ranges::views']]],
  ['set_5funion_5ffn',['set_union_fn',['../structranges_1_1views_1_1set__union__fn.html',1,'ranges::views']]],
  ['shared_5fclosure',['shared_closure',['../structranges_1_1experimental_1_1shared__closure.html',1,'ranges::experimental']]],
  ['shared_5fclosure_5fbase',['shared_closure_base',['../structranges_1_1experimental_1_1shared__closure__base.html',1,'ranges::experimental']]],
  ['shared_5ffn',['shared_fn',['../structranges_1_1experimental_1_1views_1_1shared__fn.html',1,'ranges::experimental::views']]],
  ['shared_5fview',['shared_view',['../structranges_1_1experimental_1_1shared__view.html',1,'ranges::experimental']]],
  ['sharedfn',['SharedFn',['../class_shared_fn.html',1,'']]],
  ['shuffle_5ffn',['shuffle_fn',['../structranges_1_1actions_1_1shuffle__fn.html',1,'ranges::actions']]],
  ['single_5ffn',['single_fn',['../structranges_1_1views_1_1single__fn.html',1,'ranges::views']]],
  ['single_5fview',['single_view',['../structranges_1_1single__view.html',1,'ranges']]],
  ['sized_5fiterator_5frange',['sized_iterator_range',['../structranges_1_1sized__iterator__range.html',1,'ranges']]],
  ['sized_5frange_5ftag',['sized_range_tag',['../structranges_1_1sized__range__tag.html',1,'ranges']]],
  ['sized_5fsentinel_5ftag',['sized_sentinel_tag',['../structranges_1_1sized__sentinel__tag.html',1,'ranges']]],
  ['slice_5fbase_5ffn',['slice_base_fn',['../structranges_1_1views_1_1slice__base__fn.html',1,'ranges::views']]],
  ['slice_5ffn',['slice_fn',['../structranges_1_1actions_1_1slice__fn.html',1,'ranges::actions::slice_fn'],['../structranges_1_1views_1_1slice__fn.html',1,'ranges::views::slice_fn']]],
  ['slice_5fview',['slice_view',['../structranges_1_1slice__view.html',1,'ranges']]],
  ['sliding_5fbase_5ffn',['sliding_base_fn',['../structranges_1_1views_1_1sliding__base__fn.html',1,'ranges::views']]],
  ['sliding_5ffn',['sliding_fn',['../structranges_1_1views_1_1sliding__fn.html',1,'ranges::views']]],
  ['sliding_5fview',['sliding_view',['../structranges_1_1sliding__view.html',1,'ranges']]],
  ['sliding_5fview_3c_20rng_2c_20sliding_5fview_5fdetail_3a_3acache_3a_3afirst_20_3e',['sliding_view&lt; Rng, sliding_view_detail::cache::first &gt;',['../structranges_1_1sliding__view_3_01_rng_00_01sliding__view__detail_1_1cache_1_1first_01_4.html',1,'ranges']]],
  ['sliding_5fview_3c_20rng_2c_20sliding_5fview_5fdetail_3a_3acache_3a_3alast_20_3e',['sliding_view&lt; Rng, sliding_view_detail::cache::last &gt;',['../structranges_1_1sliding__view_3_01_rng_00_01sliding__view__detail_1_1cache_1_1last_01_4.html',1,'ranges']]],
  ['sliding_5fview_3c_20rng_2c_20sliding_5fview_5fdetail_3a_3acache_3a_3anone_20_3e',['sliding_view&lt; Rng, sliding_view_detail::cache::none &gt;',['../structranges_1_1sliding__view_3_01_rng_00_01sliding__view__detail_1_1cache_1_1none_01_4.html',1,'ranges']]],
  ['sort_5ffn',['sort_fn',['../structranges_1_1actions_1_1sort__fn.html',1,'ranges::actions']]],
  ['span',['span',['../structranges_1_1span.html',1,'ranges']]],
  ['split_5fbase_5ffn',['split_base_fn',['../structranges_1_1views_1_1split__base__fn.html',1,'ranges::views']]],
  ['split_5ffn',['split_fn',['../structranges_1_1actions_1_1split__fn.html',1,'ranges::actions::split_fn'],['../structranges_1_1views_1_1split__fn.html',1,'ranges::views::split_fn']]],
  ['split_5fview',['split_view',['../structranges_1_1split__view.html',1,'ranges']]],
  ['split_5fwhen_5fbase_5ffn',['split_when_base_fn',['../structranges_1_1views_1_1split__when__base__fn.html',1,'ranges::views']]],
  ['split_5fwhen_5ffn',['split_when_fn',['../structranges_1_1actions_1_1split__when__fn.html',1,'ranges::actions::split_when_fn'],['../structranges_1_1views_1_1split__when__fn.html',1,'ranges::views::split_when_fn']]],
  ['split_5fwhen_5fview',['split_when_view',['../structranges_1_1split__when__view.html',1,'ranges']]],
  ['stable_5fsort_5ffn',['stable_sort_fn',['../structranges_1_1actions_1_1stable__sort__fn.html',1,'ranges::actions']]],
  ['static_5fconst',['static_const',['../structranges_1_1static__const.html',1,'ranges']]],
  ['std_5fiterator_5ftraits',['std_iterator_traits',['../classranges_1_1detail_1_1std__iterator__traits.html',1,'']]],
  ['stride_5fbase_5ffn',['stride_base_fn',['../structranges_1_1views_1_1stride__base__fn.html',1,'ranges::views']]],
  ['stride_5ffn',['stride_fn',['../structranges_1_1actions_1_1stride__fn.html',1,'ranges::actions::stride_fn'],['../structranges_1_1views_1_1stride__fn.html',1,'ranges::views::stride_fn']]],
  ['stride_5fview',['stride_view',['../structranges_1_1stride__view.html',1,'ranges']]],
  ['subrange',['subrange',['../structranges_1_1subrange.html',1,'ranges']]]
];
