var searchData=
[
  ['sample_5ffn',['sample_fn',['../structranges_1_1sample__fn.html',1,'ranges::sample_fn'],['../structranges_1_1view_1_1sample__fn.html',1,'ranges::view::sample_fn']]],
  ['sample_5fview',['sample_view',['../classranges_1_1sample__view.html',1,'ranges']]],
  ['scope_5fexit',['scope_exit',['../structranges_1_1scope__exit.html',1,'ranges']]],
  ['search_5ffn',['search_fn',['../structranges_1_1search__fn.html',1,'ranges']]],
  ['search_5fn_5ffn',['search_n_fn',['../structranges_1_1search__n__fn.html',1,'ranges']]],
  ['semiregular',['semiregular',['../structranges_1_1semiregular.html',1,'ranges']]],
  ['semiregular_3c_20t_20_26_20_3e',['semiregular&lt; T &amp; &gt;',['../structranges_1_1semiregular_3_01_t_01_6_01_4.html',1,'ranges']]],
  ['semiregular_3c_20t_20_26_26_20_3e',['semiregular&lt; T &amp;&amp; &gt;',['../structranges_1_1semiregular_3_01_t_01_6_6_01_4.html',1,'ranges']]],
  ['set',['set',['../classset.html',1,'']]],
  ['set_5fdifference_5ffn',['set_difference_fn',['../structranges_1_1set__difference__fn.html',1,'ranges::set_difference_fn'],['../structranges_1_1view_1_1set__difference__fn.html',1,'ranges::view::set_difference_fn']]],
  ['set_5fintersection_5ffn',['set_intersection_fn',['../structranges_1_1set__intersection__fn.html',1,'ranges::set_intersection_fn'],['../structranges_1_1view_1_1set__intersection__fn.html',1,'ranges::view::set_intersection_fn']]],
  ['set_5fsymmetric_5fdifference_5ffn',['set_symmetric_difference_fn',['../structranges_1_1set__symmetric__difference__fn.html',1,'ranges::set_symmetric_difference_fn'],['../structranges_1_1view_1_1set__symmetric__difference__fn.html',1,'ranges::view::set_symmetric_difference_fn']]],
  ['set_5funion_5ffn',['set_union_fn',['../structranges_1_1set__union__fn.html',1,'ranges::set_union_fn'],['../structranges_1_1view_1_1set__union__fn.html',1,'ranges::view::set_union_fn']]],
  ['shared_5ffn',['shared_fn',['../structranges_1_1experimental_1_1view_1_1shared__fn.html',1,'ranges::experimental::view']]],
  ['shared_5fview',['shared_view',['../structranges_1_1experimental_1_1shared__view.html',1,'ranges::experimental']]],
  ['shuffle_5ffn',['shuffle_fn',['../structranges_1_1action_1_1shuffle__fn.html',1,'ranges::action::shuffle_fn'],['../structranges_1_1shuffle__fn.html',1,'ranges::shuffle_fn']]],
  ['single_5ffn',['single_fn',['../structranges_1_1view_1_1single__fn.html',1,'ranges::view']]],
  ['single_5fview',['single_view',['../structranges_1_1single__view.html',1,'ranges']]],
  ['sized_5fiterator_5frange',['sized_iterator_range',['../structranges_1_1sized__iterator__range.html',1,'ranges']]],
  ['slice_5ffn',['slice_fn',['../structranges_1_1action_1_1slice__fn.html',1,'ranges::action::slice_fn'],['../structranges_1_1view_1_1slice__fn.html',1,'ranges::view::slice_fn']]],
  ['slice_5fview',['slice_view',['../structranges_1_1slice__view.html',1,'ranges']]],
  ['sliding_5ffn',['sliding_fn',['../structranges_1_1view_1_1sliding__fn.html',1,'ranges::view']]],
  ['sliding_5fview',['sliding_view',['../structranges_1_1sliding__view.html',1,'ranges']]],
  ['sliding_5fview_3c_20rng_2c_20sliding_5fview_5fdetail_3a_3acache_3a_3afirst_20_3e',['sliding_view&lt; Rng, sliding_view_detail::cache::first &gt;',['../structranges_1_1sliding__view_3_01_rng_00_01sliding__view__detail_1_1cache_1_1first_01_4.html',1,'ranges']]],
  ['sliding_5fview_3c_20rng_2c_20sliding_5fview_5fdetail_3a_3acache_3a_3alast_20_3e',['sliding_view&lt; Rng, sliding_view_detail::cache::last &gt;',['../structranges_1_1sliding__view_3_01_rng_00_01sliding__view__detail_1_1cache_1_1last_01_4.html',1,'ranges']]],
  ['sliding_5fview_3c_20rng_2c_20sliding_5fview_5fdetail_3a_3acache_3a_3anone_20_3e',['sliding_view&lt; Rng, sliding_view_detail::cache::none &gt;',['../structranges_1_1sliding__view_3_01_rng_00_01sliding__view__detail_1_1cache_1_1none_01_4.html',1,'ranges']]],
  ['sort_5ffn',['sort_fn',['../structranges_1_1action_1_1sort__fn.html',1,'ranges::action::sort_fn'],['../structranges_1_1sort__fn.html',1,'ranges::sort_fn']]],
  ['sort_5fheap_5ffn',['sort_heap_fn',['../structranges_1_1sort__heap__fn.html',1,'ranges']]],
  ['span',['span',['../structranges_1_1span.html',1,'ranges']]],
  ['split_5ffn',['split_fn',['../structranges_1_1action_1_1split__fn.html',1,'ranges::action::split_fn'],['../structranges_1_1view_1_1split__fn.html',1,'ranges::view::split_fn']]],
  ['split_5fview',['split_view',['../structranges_1_1split__view.html',1,'ranges']]],
  ['split_5fwhen_5ffn',['split_when_fn',['../structranges_1_1action_1_1split__when__fn.html',1,'ranges::action::split_when_fn'],['../structranges_1_1view_1_1split__when__fn.html',1,'ranges::view::split_when_fn']]],
  ['split_5fwhen_5fview',['split_when_view',['../structranges_1_1split__when__view.html',1,'ranges']]],
  ['stable_5fpartition_5ffn',['stable_partition_fn',['../structranges_1_1stable__partition__fn.html',1,'ranges']]],
  ['stable_5fsort_5ffn',['stable_sort_fn',['../structranges_1_1action_1_1stable__sort__fn.html',1,'ranges::action::stable_sort_fn'],['../structranges_1_1stable__sort__fn.html',1,'ranges::stable_sort_fn']]],
  ['starts_5fwith_5ffn',['starts_with_fn',['../structranges_1_1starts__with__fn.html',1,'ranges']]],
  ['starts_5fwith_5fresult',['starts_with_result',['../structranges_1_1starts__with__result.html',1,'ranges']]],
  ['static_5fconst',['static_const',['../structranges_1_1static__const.html',1,'ranges']]],
  ['std_5fiterator_5ftraits',['std_iterator_traits',['../classranges_1_1detail_1_1std__iterator__traits.html',1,'']]],
  ['stride_5ffn',['stride_fn',['../structranges_1_1action_1_1stride__fn.html',1,'ranges::action::stride_fn'],['../structranges_1_1view_1_1stride__fn.html',1,'ranges::view::stride_fn']]],
  ['stride_5fview',['stride_view',['../structranges_1_1stride__view.html',1,'ranges']]],
  ['subrange',['subrange',['../structranges_1_1subrange.html',1,'ranges']]],
  ['swap_5franges_5ffn',['swap_ranges_fn',['../structranges_1_1swap__ranges__fn.html',1,'ranges']]]
];
