var searchData=
[
  ['contains',['contains',['../group__group-algorithms.html#ga20cc9a6f2eaf8f090470a5e87c7e8264',1,'ranges::contains(I first, S last, const T &amp;val, P proj={}) -&gt; bool requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; I, P &gt;, const T * &gt;'],['../group__group-algorithms.html#ga01a62ccee18d1fec2e634bb3141e8582',1,'ranges::contains(Rng &amp;&amp;rng, const T &amp;val, P proj={}) -&gt; bool requires input_range&lt; Rng &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; iterator_t&lt; Rng &gt;, P &gt;, const T * &gt;']]],
  ['copy',['copy',['../group__group-algorithms.html#ga83cdf5c653cd6f7b6d18deaab905cdd9',1,'ranges::copy(I first, S last, O out) -&gt; copy_result&lt; I, O &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirectly_copyable&lt; I, O &gt;'],['../group__group-algorithms.html#ga917adb24d7ee65882cf576a5a4c5228d',1,'ranges::copy(Rng &amp;&amp;rng, O out) -&gt; copy_result&lt; safe_iterator_t&lt; Rng &gt;, O &gt; requires input_range&lt; Rng &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirectly_copyable&lt; iterator_t&lt; Rng &gt;, O &gt;']]],
  ['copy_5fbackward',['copy_backward',['../group__group-algorithms.html#ga1440e2b669271bb83e34324338757caf',1,'ranges::copy_backward(I first, S end_, O out) -&gt; copy_backward_result&lt; I, O &gt; requires bidirectional_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;bidirectional_iterator&lt; O &gt; &amp;&amp;indirectly_copyable&lt; I, O &gt;'],['../group__group-algorithms.html#ga908b242ebc91d53a3f38ce24d01493b1',1,'ranges::copy_backward(Rng &amp;&amp;rng, O out) -&gt; copy_backward_result&lt; safe_iterator_t&lt; Rng &gt;, O &gt; requires bidirectional_range&lt; Rng &gt; &amp;&amp;bidirectional_iterator&lt; O &gt; &amp;&amp;indirectly_copyable&lt; iterator_t&lt; Rng &gt;, O &gt;']]],
  ['copy_5fif',['copy_if',['../group__group-algorithms.html#ga9c7793e127e9f16451b8e2869ca8be78',1,'ranges::copy_if(I first, S last, O out, F pred, P proj=P{}) -&gt; copy_if_result&lt; I, O &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; I, P &gt;&gt; &amp;&amp;indirectly_copyable&lt; I, O &gt;'],['../group__group-algorithms.html#gacf2c0297eeb25e9a6fd9d1323f4eb967',1,'ranges::copy_if(Rng &amp;&amp;rng, O out, F pred, P proj=P{}) -&gt; copy_if_result&lt; safe_iterator_t&lt; Rng &gt;, O &gt; requires input_range&lt; Rng &gt; &amp;&amp;weakly_incrementable&lt; O &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt; &amp;&amp;indirectly_copyable&lt; iterator_t&lt; Rng &gt;, O &gt;']]],
  ['copy_5fn',['copy_n',['../group__group-algorithms.html#ga5dfbdb6265d19283095c021a2891bc5d',1,'ranges']]],
  ['count',['count',['../group__group-algorithms.html#ga0a6302f276cdf98372e30f45d10ae3a4',1,'ranges::count(I first, S last, V const &amp;val, P proj=P{}) -&gt; iter_difference_t&lt; I &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; I, P &gt;, V const * &gt;'],['../group__group-algorithms.html#gae2ef1075d6f1f102246b50dff5e01eda',1,'ranges::count(Rng &amp;&amp;rng, V const &amp;val, P proj=P{}) -&gt; iter_difference_t&lt; iterator_t&lt; Rng &gt;&gt; requires input_range&lt; Rng &gt; &amp;&amp;indirect_relation&lt; equal_to, projected&lt; iterator_t&lt; Rng &gt;, P &gt;, V const * &gt;']]],
  ['count_5fif',['count_if',['../group__group-algorithms.html#gaa6d7932d258fee27a78a08afefdeda1b',1,'ranges::count_if(I first, S last, R pred, P proj=P{}) -&gt; iter_difference_t&lt; I &gt; requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_unary_predicate&lt; R, projected&lt; I, P &gt;&gt;'],['../group__group-algorithms.html#ga8a066f39ca76bf1389b93ffd55720f7e',1,'ranges::count_if(Rng &amp;&amp;rng, R pred, P proj=P{}) -&gt; iter_difference_t&lt; iterator_t&lt; Rng &gt;&gt; requires input_range&lt; Rng &gt; &amp;&amp;indirect_unary_predicate&lt; R, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt;']]],
  ['cycled_5fview',['cycled_view',['../structranges_1_1cycled__view.html#aa31042ba35997c191f70557600daba1e',1,'ranges::cycled_view']]]
];
