var searchData=
[
  ['adjacent_5ffind_1916',['adjacent_find',['../group__group-algorithms.html#ga144612fc146861f9979b3e6e25268732',1,'ranges::adjacent_find(I first, S last, C pred=C{}, P proj=P{}) -&gt; I requires forward_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_relation&lt; C, projected&lt; I, P &gt;&gt;'],['../group__group-algorithms.html#gac18173d384f683bde768744166ae5907',1,'ranges::adjacent_find(Rng &amp;&amp;rng, C pred=C{}, P proj=P{}) -&gt; safe_iterator_t&lt; Rng &gt; requires forward_range&lt; Rng &gt; &amp;&amp;indirect_relation&lt; C, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt;']]],
  ['adjacent_5fremove_5fif_1917',['adjacent_remove_if',['../group__group-algorithms.html#ga2d08c6a9c28092deaa0a55dfc92fd1cd',1,'ranges::adjacent_remove_if(I first, S last, Pred pred={}, Proj proj={}) -&gt; I requires permutable&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_relation&lt; Pred, projected&lt; I, Proj &gt;&gt;'],['../group__group-algorithms.html#ga7eb3423653bb64e8fec6c9103d0b2fd9',1,'ranges::adjacent_remove_if(Rng &amp;&amp;rng, Pred pred, Proj proj={}) -&gt; safe_iterator_t&lt; Rng &gt; requires forward_range&lt; Rng &gt; &amp;&amp;indirect_relation&lt; Pred, projected&lt; iterator_t&lt; Rng &gt;, Proj &gt;&gt; &amp;&amp;permutable&lt; iterator_t&lt; Rng &gt;&gt;']]],
  ['all_5fof_1918',['all_of',['../group__group-algorithms.html#gab0fb576d41b10d5dea5641a244cca92b',1,'ranges::all_of(I first, S last, F pred, P proj=P{}) -&gt; bool requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; I, P &gt;&gt;'],['../group__group-algorithms.html#ga264d1b1c80f6f675d5c708d9b044a7f0',1,'ranges::all_of(Rng &amp;&amp;rng, F pred, P proj=P{}) -&gt; bool requires input_range&lt; Rng &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt;']]],
  ['any_5fcast_1919',['any_cast',['../any_8hpp.html#aae3803742d146c83e9bd0dbc6e8092d3',1,'ranges::any_cast(any &amp;)'],['../any_8hpp.html#ae672daf3d94a592c4ae43704e5951bb9',1,'ranges::any_cast(any const &amp;x)'],['../any_8hpp.html#a810edb7521f99741713cf389fd7c9047',1,'ranges::any_cast(any &amp;&amp;x)'],['../any_8hpp.html#afeab7507ae7b5a41c37fa593e528f176',1,'ranges::any_cast(any *p) noexcept'],['../any_8hpp.html#a6a0791fb2ebd96d2892e05c0aecd6481',1,'ranges::any_cast(any const *p) noexcept']]],
  ['any_5fof_1920',['any_of',['../group__group-algorithms.html#ga279ac588c4dac30d1bf061feaf6dac8a',1,'ranges::any_of(I first, S last, F pred, P proj=P{}) -&gt; bool requires input_iterator&lt; I &gt; &amp;&amp;sentinel_for&lt; S, I &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; I, P &gt;&gt;'],['../group__group-algorithms.html#gad75b386493da30a175489379ad3d44ed',1,'ranges::any_of(Rng &amp;&amp;rng, F pred, P proj=P{}) -&gt; bool requires input_range&lt; Rng &gt; &amp;&amp;indirect_unary_predicate&lt; F, projected&lt; iterator_t&lt; Rng &gt;, P &gt;&gt;']]],
  ['at_1921',['at',['../structranges_1_1view__interface.html#a5018282ef9e35b1772f97df3ea23b507',1,'ranges::view_interface::at(range_difference_t&lt; D&lt; True &gt;&gt; n) -&gt; range_reference_t&lt; D&lt; True &gt;&gt; requires True &amp;&amp;random_access_range&lt; D&lt; True &gt;&gt; &amp;&amp;sized_range&lt; D&lt; True &gt;&gt;'],['../structranges_1_1view__interface.html#a67b5f196dd9d8c16f03a551c23776886',1,'ranges::view_interface::at(range_difference_t&lt; D&lt; True &gt;&gt; n) const -&gt; range_reference_t&lt; D&lt; True &gt; const &gt; requires True &amp;&amp;random_access_range&lt; D&lt; True &gt; const &gt; &amp;&amp;sized_range&lt; D&lt; True &gt; const &gt;']]]
];
